version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/backend.Dockerfile
    container_name: helpdesk-backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/frontend.Dockerfile
    container_name: helpdesk-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/sse
    env_file:
      - .env
